### ISSUE TITLE
Index.totalTasks未修改   +   断点续传问题

### ISSUE THREAD

**Issue by zhangyixing1007** [Dragon1573/Multitask-Downloader#1]
作者你好，我是在csdn上看到你的帖子过来的。我把你的代码下下来玩耍了一下，发现了以下两点，希望可以跟你讨论一下。

1. Index.totalTasks这个变量从始至终都没有修改。建议在DownThread.java适当位置添加
Index.totalTasks++；
Index.totalTasks--；
否则变量MAX_TASKS还有NewTaskListener.java中的筛选语句
else if (Index.totalTasks + 1 > Index.MAXTASKS)
就没有意义了。

2. 然后还发现了一个bug，有时候断点续传会直接显示 “该资源不存在”，但是同一个资源第二次下载就可以了。应该是DownThread.java中的run()的try版块出了问题，但是我左看右看也没有看出问题在哪里，可以跟您讨论一下嘛？
我这里说的断点续传具体指
下载文件abc -> 文件abc没有下载完毕，关闭下载器 -> 再次打开下载器 -> 输入相同的下载地址，在文件选择中选择那个没有下完的文件 -> 弹出对话框：资源不存在

但第二遍对同一个文件abc执行如下操作
再次打开下载器 -> 输入相同的下载地址，在文件选择中选择那个没有下完的文件
基本上就可以断点续传了。这是为啥。。。。

希望可以得到您的回复，谢谢！

**Comment by Dragon1573** [comment]
很高兴您能在 CSDN 上找到我并尝试与我互动。

关于您反馈的问题：

1. 任务计数器异常已经在提交 78aab95 中予以修复。经我测试，此问题已被修复。
2. 在先前版本 v1.0 中，`try` 代码块中的所有异常被统一用 `Exception` 进行捕获。以 QQ for Windows 和 Anaconda-1.9.0-Linux-x86_64.sh 两个资源测试，都没有出现您提到的“资源不存在”情况、可以正常地完成断点续传。

*****

请同步 78aab95 ，并帮助我进行测试。如果发现还有其他问题，欢迎继续向我反馈，谢谢！

**Comment by Dragon1573** [comment]
@zhangyixing1007 ，你好呀～

这次更新（ e1e496a ），我完善并扩充了先前尚不完整的功能：

****

**文件匹配机制**

在上一个版本（ 78aab95 ）中，续传与覆盖的自动判断仅凭借文件大小是否一致来匹配。当本地文件 `local.dat` 未下载完远端 `remote_A.dat` 却转而下载 `remote_B.dat` 时，程序不能确定尚不完整的 `local.dat` 并不是 `remote_B.dat` 的一部分，从而从断点处接续下载 `remote_B.dat` 。这使得最终的 `local.dat` 前一部分来自 `remote_A.dat` ，而后一部分来自 `remote_B.dat` 最终的文件仍然是不完整的。

通过本次更新，我借鉴了现有商用下载工具使用“残缺文件标记”的方式，创建与目标数据文件配套的“元数据”文件。我所创建的元数据文件以 `*.sha` 为文件后缀名，以文本的形式记录配套数据文件的URL来源。当下载线程随程序意外终止时， `*.sha` 会与尚不完整的数据文件一起保留在磁盘上。只有当数据程序被完整地下载后， `*.sha` 才会被下载线程删除。

**默认文件名**

在上一个版本中，另存为的本地文件名及其后缀名只能由用户输入。当用户没有输入后缀名或后缀名与远端不一致，尽管下载后的数据是完整的，但由于文件类型的错误标记，用户仍无法打开本地文件。

本次更新加入了默认文件名机制，在“另存为”面板初始化弹出时，将远端的文件名作为本地文件的默认名。这样，用户就可以在不主动填写文件名的情况下直接以同名文件的方式进行下载。

**后缀锁**

为了防止文件类型的错误标记，此次更新引入了“后缀锁”的概念。通过自动识别远端资源的后缀名，借助 [`JFileChooser`](https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/JFileChooser.html) 提供的后缀名过滤机制将错误的后缀名统一进行屏蔽。同时，后缀锁会为后缀名不匹配的文件统一补齐后缀名，用户即可在省略指定后缀名的情况下正常完成资源下载。

****

感谢您提出的意见和建议。
